apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: k8s-policy-controller
resources:
- gcpauthpolicyprofile
- nodepolicyprofile
components:
- namespace
