apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcpauthpolicyprofile-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: gcpauthpolicyprofile-controller
      app.kubernetes.io/name: gcpauthpolicyprofile-controller
  template:
    metadata:
      labels:
        app: k8s-policy-controller
        instance: gcpauthpolicyprofile
        app.kubernetes.io/instance: gcpauthpolicyprofile-controller
        app.kubernetes.io/name: gcpauthpolicyprofile-controller
    spec:
      containers:
      - args:
        - --kind=gcpauthpolicyprofile
        image: k8s-policy-controller:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics-server
            scheme: HTTP
        name: k8s-policy-controller
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 8080
          name: metrics-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics-server
            scheme: HTTP
        resources: {}
        securityContext: {}
      securityContext: {}
      serviceAccountName: gcpauthpolicyprofile-controller
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: gcpauthpolicyprofile-controller-tls
