kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/instance: gcpauthpolicyprofile
resources:
- gcpauthpolicyprofile-controller-certificate.yaml
- gcpauthpolicyprofile-controller-clusterrole.yaml
- gcpauthpolicyprofile-controller-crb.yaml
- gcpauthpolicyprofile-controller-deploy.yaml
- gcpauthpolicyprofile-controller-sa.yaml
- gcpauthpolicyprofile-controller-svc.yaml
- gcpauthpolicyprofile-mutwebhookcfg.yaml
- profiles.gcpauthpolicy.nuxeo.io-crd.yaml
