
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
  creationTimestamp: null
  name: nodepolicyprofiles.noodepolicies.softonic.io
spec:
  group: noodepolicies.softonic.io
  names:
    kind: NodePolicyProfile
    listKind: NodePolicyProfileList
    plural: nodepolicyprofiles
    singular: nodepolicyprofile
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: NodePolicyProfile is the Schema for the nodepolicyprofiles API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        nodeAffinity:
          description: Node affinity is a group of node affinity scheduling rules.
          properties:
            preferredDuringSchedulingIgnoredDuringExecution:
              description: The scheduler will prefer to schedule pods to nodes that
                satisfy the affinity expressions specified by this field, but it may
                choose a node that violates one or more of the expressions. The node
                that is most preferred is the one with the greatest sum of weights,
                i.e. for each node that meets all of the scheduling requirements (resource
                request, requiredDuringScheduling affinity expressions, etc.), compute
                a sum by iterating through the elements of this field and adding "weight"
                to the sum if the node matches the corresponding matchExpressions;
                the node(s) with the highest sum are the most preferred.
              items:
                description: An empty preferred scheduling term matches all objects
                  with implicit weight 0 (i.e. it's a no-op). A null preferred scheduling
                  term matches no objects (i.e. is also a no-op).
                properties:
                  preference:
                    description: A node selector term, associated with the corresponding
                      weight.
                    properties:
                      matchExpressions:
                        description: A list of node selector requirements by node's
                          labels.
                        items:
                          description: A node selector requirement is a selector that
                            contains values, a key, and an operator that relates the
                            key and values.
                          properties:
                            key:
                              description: The label key that the selector applies
                                to.
                              type: string
                            operator:
                              description: Represents a key's relationship to a set
                                of values. Valid operators are In, NotIn, Exists,
                                DoesNotExist. Gt, and Lt.
                              type: string
                            values:
                              description: An array of string values. If the operator
                                is In or NotIn, the values array must be non-empty.
                                If the operator is Exists or DoesNotExist, the values
                                array must be empty. If the operator is Gt or Lt,
                                the values array must have a single element, which
                                will be interpreted as an integer. This array is replaced
                                during a strategic merge patch.
                              items:
                                type: string
                              type: array
                          required:
                          - key
                          - operator
                          type: object
                        type: array
                      matchFields:
                        description: A list of node selector requirements by node's
                          fields.
                        items:
                          description: A node selector requirement is a selector that
                            contains values, a key, and an operator that relates the
                            key and values.
                          properties:
                            key:
                              description: The label key that the selector applies
                                to.
                              type: string
                            operator:
                              description: Represents a key's relationship to a set
                                of values. Valid operators are In, NotIn, Exists,
                                DoesNotExist. Gt, and Lt.
                              type: string
                            values:
                              description: An array of string values. If the operator
                                is In or NotIn, the values array must be non-empty.
                                If the operator is Exists or DoesNotExist, the values
                                array must be empty. If the operator is Gt or Lt,
                                the values array must have a single element, which
                                will be interpreted as an integer. This array is replaced
                                during a strategic merge patch.
                              items:
                                type: string
                              type: array
                          required:
                          - key
                          - operator
                          type: object
                        type: array
                    type: object
                  weight:
                    description: Weight associated with matching the corresponding
                      nodeSelectorTerm, in the range 1-100.
                    format: int32
                    type: integer
                required:
                - preference
                - weight
                type: object
              type: array
            requiredDuringSchedulingIgnoredDuringExecution:
              description: If the affinity requirements specified by this field are
                not met at scheduling time, the pod will not be scheduled onto the
                node. If the affinity requirements specified by this field cease to
                be met at some point during pod execution (e.g. due to an update),
                the system may or may not try to eventually evict the pod from its
                node.
              properties:
                nodeSelectorTerms:
                  description: Required. A list of node selector terms. The terms
                    are ORed.
                  items:
                    description: A null or empty node selector term matches no objects.
                      The requirements of them are ANDed. The TopologySelectorTerm
                      type implements a subset of the NodeSelectorTerm.
                    properties:
                      matchExpressions:
                        description: A list of node selector requirements by node's
                          labels.
                        items:
                          description: A node selector requirement is a selector that
                            contains values, a key, and an operator that relates the
                            key and values.
                          properties:
                            key:
                              description: The label key that the selector applies
                                to.
                              type: string
                            operator:
                              description: Represents a key's relationship to a set
                                of values. Valid operators are In, NotIn, Exists,
                                DoesNotExist. Gt, and Lt.
                              type: string
                            values:
                              description: An array of string values. If the operator
                                is In or NotIn, the values array must be non-empty.
                                If the operator is Exists or DoesNotExist, the values
                                array must be empty. If the operator is Gt or Lt,
                                the values array must have a single element, which
                                will be interpreted as an integer. This array is replaced
                                during a strategic merge patch.
                              items:
                                type: string
                              type: array
                          required:
                          - key
                          - operator
                          type: object
                        type: array
                      matchFields:
                        description: A list of node selector requirements by node's
                          fields.
                        items:
                          description: A node selector requirement is a selector that
                            contains values, a key, and an operator that relates the
                            key and values.
                          properties:
                            key:
                              description: The label key that the selector applies
                                to.
                              type: string
                            operator:
                              description: Represents a key's relationship to a set
                                of values. Valid operators are In, NotIn, Exists,
                                DoesNotExist. Gt, and Lt.
                              type: string
                            values:
                              description: An array of string values. If the operator
                                is In or NotIn, the values array must be non-empty.
                                If the operator is Exists or DoesNotExist, the values
                                array must be empty. If the operator is Gt or Lt,
                                the values array must have a single element, which
                                will be interpreted as an integer. This array is replaced
                                during a strategic merge patch.
                              items:
                                type: string
                              type: array
                          required:
                          - key
                          - operator
                          type: object
                        type: array
                    type: object
                  type: array
              required:
              - nodeSelectorTerms
              type: object
          type: object
        nodeSelector:
          description: A node selector represents the union of the results of one
            or more label queries over a set of nodes; that is, it represents the
            OR of the selectors represented by the node selector terms.
          properties:
            nodeSelectorTerms:
              description: Required. A list of node selector terms. The terms are
                ORed.
              items:
                description: A null or empty node selector term matches no objects.
                  The requirements of them are ANDed. The TopologySelectorTerm type
                  implements a subset of the NodeSelectorTerm.
                properties:
                  matchExpressions:
                    description: A list of node selector requirements by node's labels.
                    items:
                      description: A node selector requirement is a selector that
                        contains values, a key, and an operator that relates the key
                        and values.
                      properties:
                        key:
                          description: The label key that the selector applies to.
                          type: string
                        operator:
                          description: Represents a key's relationship to a set of
                            values. Valid operators are In, NotIn, Exists, DoesNotExist.
                            Gt, and Lt.
                          type: string
                        values:
                          description: An array of string values. If the operator
                            is In or NotIn, the values array must be non-empty. If
                            the operator is Exists or DoesNotExist, the values array
                            must be empty. If the operator is Gt or Lt, the values
                            array must have a single element, which will be interpreted
                            as an integer. This array is replaced during a strategic
                            merge patch.
                          items:
                            type: string
                          type: array
                      required:
                      - key
                      - operator
                      type: object
                    type: array
                  matchFields:
                    description: A list of node selector requirements by node's fields.
                    items:
                      description: A node selector requirement is a selector that
                        contains values, a key, and an operator that relates the key
                        and values.
                      properties:
                        key:
                          description: The label key that the selector applies to.
                          type: string
                        operator:
                          description: Represents a key's relationship to a set of
                            values. Valid operators are In, NotIn, Exists, DoesNotExist.
                            Gt, and Lt.
                          type: string
                        values:
                          description: An array of string values. If the operator
                            is In or NotIn, the values array must be non-empty. If
                            the operator is Exists or DoesNotExist, the values array
                            must be empty. If the operator is Gt or Lt, the values
                            array must have a single element, which will be interpreted
                            as an integer. This array is replaced during a strategic
                            merge patch.
                          items:
                            type: string
                          type: array
                      required:
                      - key
                      - operator
                      type: object
                    type: array
                type: object
              type: array
          required:
          - nodeSelectorTerms
          type: object
        spec:
          description: NodePolicyProfileSpec defines the desired state of NodePolicyProfile
          properties:
            foo:
              description: Foo is an example field of NodePolicyProfile. Edit NodePolicyProfile_types.go
                to remove/update
              type: string
          type: object
        status:
          description: NodePolicyProfileStatus defines the observed state of NodePolicyProfile
          type: object
        tolerations:
          items:
            description: The pod this Toleration is attached to tolerates any taint
              that matches the triple <key,value,effect> using the matching operator
              <operator>.
            properties:
              effect:
                description: Effect indicates the taint effect to match. Empty means
                  match all taint effects. When specified, allowed values are NoSchedule,
                  PreferNoSchedule and NoExecute.
                type: string
              key:
                description: Key is the taint key that the toleration applies to.
                  Empty means match all taint keys. If the key is empty, operator
                  must be Exists; this combination means to match all values and all
                  keys.
                type: string
              operator:
                description: Operator represents a key's relationship to the value.
                  Valid operators are Exists and Equal. Defaults to Equal. Exists
                  is equivalent to wildcard for value, so that a pod can tolerate
                  all taints of a particular category.
                type: string
              tolerationSeconds:
                description: TolerationSeconds represents the period of time the toleration
                  (which must be of effect NoExecute, otherwise this field is ignored)
                  tolerates the taint. By default, it is not set, which means tolerate
                  the taint forever (do not evict). Zero and negative values will
                  be treated as 0 (evict immediately) by the system.
                format: int64
                type: integer
              value:
                description: Value is the taint value the toleration matches to. If
                  the operator is Exists, the value should be empty, otherwise just
                  a regular string.
                type: string
            type: object
          type: array
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
